//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.22 at 09:10:09 AM GMT 
//


package edu.cuhk.hccl.data;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.cuhk.hccl.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.cuhk.hccl.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Sentences.Sentence.AspectCategories }
     * 
     */
    public Sentences.Sentence.AspectCategories createSentencesSentenceAspectCategories() {
        return new Sentences.Sentence.AspectCategories();
    }

    /**
     * Create an instance of {@link Sentences.Sentence.AspectTerms }
     * 
     */
    public Sentences.Sentence.AspectTerms createSentencesSentenceAspectTerms() {
        return new Sentences.Sentence.AspectTerms();
    }

    /**
     * Create an instance of {@link Sentences }
     * 
     */
    public Sentences createSentences() {
        return new Sentences();
    }

    /**
     * Create an instance of {@link Sentences.Sentence }
     * 
     */
    public Sentences.Sentence createSentencesSentence() {
        return new Sentences.Sentence();
    }

    /**
     * Create an instance of {@link Sentences.Sentence.AspectCategories.AspectCategory }
     * 
     */
    public Sentences.Sentence.AspectCategories.AspectCategory createSentencesSentenceAspectCategoriesAspectCategory() {
        return new Sentences.Sentence.AspectCategories.AspectCategory();
    }

    /**
     * Create an instance of {@link Sentences.Sentence.AspectTerms.AspectTerm }
     * 
     */
    public Sentences.Sentence.AspectTerms.AspectTerm createSentencesSentenceAspectTermsAspectTerm() {
        return new Sentences.Sentence.AspectTerms.AspectTerm();
    }

}
